version: 0.2

phases:
  install:
    commands:
      - apt-get update && apt-get install zip
      - pip install -U -r requirements.txt
      - python3 .codebuild/codebuild.py install
  pre_build:
    commands:
      - python3 .codebuild/codebuild.py pre_build
  build:
    commands:
      - python3 .codebuild/codebuild.py build
  post_build:
    commands:
      - python3 .codebuild/codebuild.py post_build

artifacts:
  files:
    - template.json
    - configuration.json
  discard-paths: yes
  base-directory: build
