version: 0.2

phases:
  install:
    commands:
      - pip install -U requests sphinx
      - python3 codebuild.py install
  pre_build:
    commands:
      - python3 codebuild.py pre_build
  build:
    commands:
      - python3 codebuild.py build
  post_build:
    commands:
      - python3 codebuild.py post_build
artifacts:
  files:
    - template.json
    - configuration.json
  discard-paths: yes
  base-directory: build
