version: 0.2

env:
  variables:
    S3_SOURCE_BUCKET: "hyp3-in-a-box-source"

phases:
  install:
    commands:
      - pip install -U -r build_requirements.txt
      - pip install -U requirements.txt
      - pip install sphinx
      - chmod +x upload.sh
  prebuild:
    commands:
      - python -m pytest
  build:
    commands:
      - mkdir -p build/lambdas
      - python3 cloudformation/tropo/create_stack.py build/template.json
      - python3 lambdas/build_lambda.py -a -o build/lambdas/ lambdas/
  post_build:
    commands:
      - aws s3 cp s3://$S3_SOURCE_BUCKET/$MATURITY/config/configuration.json build/
      - aws s3 cp build/lambdas/ s3://$S3_SOURCE_BUCKET/$MATURITY/ --recursive --include "*"
artifacts:
  files:
    - template.json
    - configuration.json
  discard-paths: yes
  base-directory: build
