version: 0.2

env:
  variables:
    S3_SOURCE_BUCKET: "hyp3-in-a-box-source"

phases:
  install:
    commands:
      - pip install -U -r build_requirements.txt
  build:
    commands:
      - mkdir build
      - python3 cloudformation/tropo/create_stack.py build/template.json
      - python3 lambdas/build_lambda.py lambdas/send_email -o build/send_email_$CODEBUILD_RESOLVED_SOURCE_VERSION.zip
      - python3 lambdas/build_lambda.py lambdas/find_new_granules -o build/find_new_granules_$CODEBUILD_RESOLVED_SOURCE_VERSION.zip
  post_build:
    commands:
      - aws s3 cp build/send_email_$CODEBUILD_RESOLVED_SOURCE_VERSION.zip s3://$S3_SOURCE_BUCKET/$MATURITY/
      - aws s3 cp build/find_new_granules_$CODEBUILD_RESOLVED_SOURCE_VERSION.zip s3://$S3_SOURCE_BUCKET/$MATURITY/
artifacts:
  files:
    - template.json
  discard-paths: yes
  base-directory: build
