version: 0.2

phases:
  install:
    commands:
      - apt install zip
      - pip install -U requests sphinx pytest subprocess32 pytest-cov defusedxml
      - python3 .codebuild/codebuild.py install
  pre_build:
    commands:
      - python3 .codebuild/codebuild.py pre_build
  build:
    commands:
      - python3 .codebuild/codebuild.py build
  post_build:
    commands:
      - python3 .codebuild/codebuild.py post_build
artifacts:
  files:
    - template.json
    - configuration.json
  discard-paths: yes
  base-directory: build
