version: 0.2

env:
  variables:
    S3_SOURCE_BUCKET: "hyp3-in-a-box-source"

phases:
  install:
    commands:
      - curl -X POST $CODEBUILD_SOURCE_REPO_URL/statuses/$CODEBUILD_SOURCE_VERSION?access_token=$GITHUB_STATUS_TOKEN -d '{"state":"pending", "context", "continuous-integration/codebuild"}'
      - pip install -U -r build_requirements.txt
      - pip install -r requirements.txt
      - pip install sphinx
      - chmod +x upload.sh
  pre_build:
    commands:
      - python -m pytest
  build:
    commands:
      - mkdir -p build/lambdas
      - python3 cloudformation/tropo/create_stack.py build/template.json --maturity $MATURITY
      - python3 lambdas/build_lambda.py -a -o build/lambdas/ lambdas/
  post_build:
    commands:
      - aws s3 cp s3://$S3_SOURCE_BUCKET/$MATURITY/config/configuration.json build/
      - aws s3 cp build/lambdas/ s3://$S3_SOURCE_BUCKET/$MATURITY/ --recursive --include "*"
      - curl -X POST $CODEBUILD_SOURCE_REPO_URL/statuses/$CODEBUILD_SOURCE_VERSION?access_token=$GITHUB_STATUS_TOKEN -d '{"state":"success", "context", "continuous-integration/codebuild"}'
artifacts:
  files:
    - template.json
    - configuration.json
  discard-paths: yes
  base-directory: build
