version: 0.2

phases:
  install:
    commands:
      - apt-get update && apt-get install zip
      - pip install -U --no-cache-dir sphinx
      - pip install -U requests pytest subprocess32 pytest-cov defusedxml pytest-xdist pytest-timeout
      - python3 .codebuild/codebuild.py install
  pre_build:
    commands:
      - python3 .codebuild/codebuild.py pre_build
  build:
    commands:
      - python3 .codebuild/codebuild.py build
  post_build:
    commands:
      - python3 .codebuild/codebuild.py post_build

artifacts:
  files:
    - template.json
    - configuration.json
  discard-paths: yes
  base-directory: build

cache:
  paths:
    - '/root/.cache/pip/**/*'
    - '/usr/local/lib/python3.6/site-packages/**/*'
